[package]
name = "monitoring-service"
version = "0.1.0"
authors = ["Mozram <zulhilmi.ramli@outlook.my>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paho-mqtt = "0.9.1"
ctrlc = "3.1.9"
